name: Deploy to FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy Tracker (Main Website)
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: tfwelch.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./tracker/  # The folder containing your main website files
        server-dir: nzroads.tfwelch.com/  # Root of your subdomain
        
    - name: Deploy Dashboard
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: tfwelch.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dashboard/  # The folder containing your dashboard files
        server-dir: nzroads.tfwelch.com/dashboard/  # Subdirectory for the dashboard
