name: Deploy to FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy main files from tracker folder
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: tfwelch.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./tracker/
        server-dir: nzroads.tfwelch.com/

    - name: Deploy dashboard files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: tfwelch.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dashboard/
        server-dir: nzroads.tfwelch.com/dashboard/

    - name: Deploy assets
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: tfwelch.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./assets/
        server-dir: nzroads.tfwelch.com/assets/
